= Validate Stack Sequences
CurryCooky; 2022-08-31

== Topic
[quote]
----
来源：力扣（LeetCode）
链接：https://leetcode.cn/problems/validate-stack-sequences
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。
----

.*English*
Given two integer arrays pushed and popped each with distinct values, return true if this could have been the result of a sequence of push and pop operations on an initially empty stack, or false otherwise.

.*中文*
给定 pushed 和 popped 两个序列，每个序列中的 值都不重复，只有当它们可能是在最初空栈上进行的推入 push 和弹出 pop 操作序列的结果时，返回 true；否则，返回 false 。

.return true
====
[%hardbreaks]
Input: pushed = [1,2,3,4,5], popped = [4,5,3,2,1]
Output: true
Explanation: We might do the following sequence:
push(1), push(2), push(3), push(4), pop() -> 4, push(5), pop() -> 5, pop() -> 3, pop() -> 2, pop() -> 1
====

.return false

====
[%hardbreaks]
Input: pushed = [1,2,3,4,5], popped = [4,3,5,1,2]
Output: false
Explanation: 1 cannot be popped before 2.
====

== My Thoughts
We can get `pushed[0]`, and compare `popped[0]`, if they equals, we can continue compare `pushed[1]` and `popped[1]`, etc.

If find not equal element(`pushed[0]` and `pushed[0]` not equals, in example 1), we need save `pushed[0]`, and increment `pushed` index, and compare `pushed[1]` to `popped[0]`...

So, we need two index, one for `pushed`, one for `popped`. And we needed some container to save `pushed` element, I used Java, so I chose `Deque`.

.*Some Details*
. When we find not equal element, we need to judge deque whether it is empty, if not empty, we can compare the next element in deque.
. If element that pop from deque not equals `popped[n]`, and `pushed` not all tranvesal, we must push it in deque again.
. If `pushed` all tranvesal, we can't continue push, only pop.

== Show My Code
[source, java]
----
public boolean validateStackSequences(int[] pushed, int[] popped) {
    int p1 = 0, p2 = 0;
    int length = pushed.length;
    Deque<Integer> deque = new ArrayDeque<>();
    deque.push(pushed[p1++]);
    while (!deque.isEmpty()) {
        Integer pop = deque.pop();
        if (pop == popped[p2]) {
            p2++;
            // not empty, can compare deque next element
            // empty, and have next, need push next, can't 'continue'
            if (!deque.isEmpty()) {
                continue;
            }
        } else {
            // not equals, push again, but must have next number
            if (p1 < length) {
                deque.push(pop);
            }
        }
        // push next number
        if (p1 < length) {
            deque.push(pushed[p1++]);
        }
    }
    // if popped all traversal, is true
    return p2 == length;
}
----