= Design Linked List
:toc: left

== Overview
Design your implementation of the linked list. You can choose to use a singly or doubly linked list.
A node in a singly linked list should have two attributes: val and next. val is the value of the current node, and next is a pointer/reference to the next node.
If you want to use the doubly linked list, you will need one more attribute prev to indicate the previous node in the linked list. Assume all nodes in the linked list are 0-indexed.

Implement the MyLinkedList class:

MyLinkedList() Initializes the MyLinkedList object.
int get(int index) Get the value of the indexth node in the linked list. If the index is invalid, return -1.
void addAtHead(int val) Add a node of value val before the first element of the linked list. After the insertion, the new node will be the first node of the linked list.
void addAtTail(int val) Append a node of value val as the last element of the linked list.
void addAtIndex(int index, int val) Add a node of value val before the indexth node in the linked list. If index equals the length of the linked list, the node will be appended to the end of the linked list. If index is greater than the length, the node will not be inserted.
void deleteAtIndex(int index) Delete the indexth node in the linked list, if the index is valid.

____
来源：力扣（LeetCode）

链接：https://leetcode.cn/problems/design-linked-list

著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。
____

== Solution
[source, java]
----
class MyLinkedList {

    private final MyLinkedNode sentinel;

    public MyLinkedList() {
        this.sentinel = new MyLinkedNode(-1, null);
    }

    public int get(int index) {
        MyLinkedNode node = sentinel.next();
        int i = 0;
        while (node != null && i != index) {
            node = node.next();
            i++;
        }
        if (i == index && node != null) {
            return node.val();
        }
        return -1;
    }

    public void addAtHead(int val) {
        sentinel.setNext(new MyLinkedNode(val, sentinel.next()));
    }

    public void addAtTail(int val) {
        MyLinkedNode node = sentinel;
        while (node.hasNext()) {
            node = node.next();
        }
        node.setNext(new MyLinkedNode(val));
    }

    public void addAtIndex(int index, int val) {
        MyLinkedNode node = sentinel;
        int i = 0;
        while (node.hasNext() && i != index) {
            node = node.next();
            i++;
        }
        if (i != index) {
            return;
        }
        node.setNext(new MyLinkedNode(val, node.next()));
    }

    public void deleteAtIndex(int index) {
        MyLinkedNode node = sentinel;
        int i = 0;
        while (node.hasNext() && i != index) {
            node = node.next();
            i++;
        }
        if (i != index) {
            return;
        }
        MyLinkedNode next = node.next();
        if (next != null) {
            next = next.next();
        }
        node.setNext(next);
    }
}

public class MyLinkedNode {
    private final int val;

    private MyLinkedNode next;

    public MyLinkedNode(int val) {
        this.val = val;
    }

    public MyLinkedNode(int val, MyLinkedNode next) {
        this.val = val;
        this.next = next;
    }

    public void setNext(MyLinkedNode next) {
        this.next = next;
    }

    public int val() {
        return val;
    }

    public boolean hasNext() {
        return next != null;
    }

    public MyLinkedNode next() {
        return next;
    }
}
----