= Crawler Log Folder
:toc: left
Curry Cooky <currycooky@qq.com>
1.0, 2022-09-09

== Overview
____
来源：力扣（LeetCode）

链接：https://leetcode.cn/problems/crawler-log-folder

著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。
____
The Leetcode file system keeps a log each time some user performs a change folder operation.

The operations are described below:

"../" : Move to the parent folder of the current folder. (If you are already in the main folder, remain in the same folder).
"./" : Remain in the same folder.
"x/" : Move to the child folder named x (This folder is guaranteed to always exist).
You are given a list of strings logs where logs[i] is the operation performed by the user at the ith step.

The file system starts in the main folder, then the operations in logs are performed.

Return the minimum number of operations needed to go back to the main folder after the change folder operations.

== Solution
Very easy, when `x/`, result + 1, when `../`, res - 1, but cannot less than 0, and if is `./`, we didn't need to do anything. The final result is the minimum of operations.

== Code
[source, java]
----
class Solution {
    public int minOperations(String[] logs) {
        int res = 0;
        for (String log : logs) {
            switch (log) {
                case "../":
                    res = Math.max(0, res - 1);
                    break;
                case "./":
                    // 不做处理
                    break;
                default:
                    res++;
            }
        }
        return res;
    }
}
----
