= Roman to Integer
:toc: left
Curry Cooky <currycooky@qq.com>
1.0, 2022-09-09

== Overview
____
来源：力扣（LeetCode）

链接：https://leetcode.cn/problems/roman-to-integer

著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。
____
Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.
....
Symbol       Value
I             1
V             5
X             10
L             50
C             100
D             500
M             1000
....
For example, 2 is written as II in Roman numeral, just two ones added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.

Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:
....
I can be placed before V (5) and X (10) to make 4 and 9. 
X can be placed before L (50) and C (100) to make 40 and 90. 
C can be placed before D (500) and M (1000) to make 400 and 900.
....
Given a roman numeral, convert it to an integer.

== Solution
Just special handling extra six instances.

== Code
[source, java]
----
class Solution {
    private static final Map<String, Integer> map;

    static {
        map = new HashMap<>();
        map.put("I", 1);
        map.put("V", 5);
        map.put("X", 10);
        map.put("L", 50);
        map.put("C", 100);
        map.put("D", 500);
        map.put("M", 1000);
        map.put("IV", 4);
        map.put("IX", 9);
        map.put("XL", 40);
        map.put("XC", 90);
        map.put("CD", 400);
        map.put("CM", 900);
    }

    public int romanToInt(String s) {

        int res = 0;
        String last = "";
        for (int i = 0; i < s.length(); i++) {
            String c = String.valueOf(s.charAt(i));
            if ("".equals(last)) {
                res += map.get(c);
                last = c;
            } else {
                Integer num = map.get(last + c);
                if (num != null) {
                    res -= map.get(last);
                    res += num;
                    last = "";
                } else {
                    res += map.get(c);
                    last = c;
                }
            }
        }
        return res;
    }
}
----
We can write better.
[source, java]
----
class Solution {
    public int romanToInt(String s) {
        int res = 0;
        int pre = value(s.charAt(0));
        for (int i = 1; i < s.length(); i++) {
            int now = value(s.charAt(i));
            if (pre < now) {
                res -= pre;
            } else {
                res += pre;
            }
            pre = now;
        }
        return res + pre;
    }

    int value(char c) {
        switch (c) {
            case 'I': return 1;
            case 'V': return 5;
            case 'X': return 10;
            case 'L': return 50;
            case 'C': return 100;
            case 'D': return 500;
            case 'M': return 1000;
            default: return 0;
        }
    }

}
----
