= Integer to Roman
:toc: left

== Overview
____
来源：力扣（LeetCode）

链接：https://leetcode.cn/problems/integer-to-roman

著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。
____
Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.
....
Symbol       Value
I             1
V             5
X             10
L             50
C             100
D             500
M             1000
....
For example, 2 is written as II in Roman numeral, just two one's added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.

Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtraction is used:

I can be placed before V (5) and X (10) to make 4 and 9. 
X can be placed before L (50) and C (100) to make 40 and 90. 
C can be placed before D (500) and M (1000) to make 400 and 900.
Given an integer, convert it to a roman numeral.

== Solution
[source, java]
----
class Solution {
    private static final Map<Integer, Map<Integer, String>> MAP;

    static {
        MAP = new HashMap<>();
        Map<Integer, String> n0 = new HashMap<>();
        n0.put(4, "IV");
        n0.put(0, "");
        n0.put(5, "V");
        n0.put(9, "IX");
        MAP.put(0, n0);
        Map<Integer, String> n1 = new HashMap<>();
        n1.put(4, "XL");
        n1.put(0, "");
        n1.put(5, "L");
        n1.put(9, "XC");
        MAP.put(1, n1);
        Map<Integer, String> n2 = new HashMap<>();
        n2.put(4, "CD");
        n2.put(0, "");
        n2.put(5, "D");
        n2.put(9, "CM");
        MAP.put(2, n2);
        MAP.put(3, new HashMap<>());
    }

    public String intToRoman(int num) {
        int n = 0;
        List<String> list = new ArrayList<>();
        while (num != 0) {
            int i = num % 10;
            list.add(to(i, n));
            num = num / 10;
            n++;
        }
        StringBuilder stringBuilder = new StringBuilder();
        for (int i = list.size() - 1; i >= 0; i--) {
            stringBuilder.append(list.get(i));
        }
        return stringBuilder.toString();
    }

    String to(int i, int n) {
        String s = MAP.get(n).get(i);
        if (s != null) {
            return s;
        }
        if (i < 5) {
            return f(i, n);
        }
        return val(n + 5) + f(i - 5, n);
    }

    String f(int i, int n) {
        StringBuilder stringBuilder = new StringBuilder();
        for (int j = 0; j < i; j++) {
            stringBuilder.append(val(n));
        }
        return stringBuilder.toString();
    }

    String val(int n) {
        switch (n) {
            case 0:
                return "I";
            case 1:
                return "X";
            case 2:
                return "C";
            case 3:
                return "M";
            case 5:
                return "V";
            case 6:
                return "L";
            case 7:
                return "D";
            default:
                return "";
        }
    }

}
----

[source, java]
----
class Solution {
    private static final int[] values = {1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1};
    private static final String[] romans = {"M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"};

    public String intToRoman(int num) {
        StringBuilder stringBuilder = new StringBuilder();
        for (int i = 0, length = values.length; i < length; i++) {
            while (num >= values[i]) {
                stringBuilder.append(romans[i]);
                num = num - values[i];
            }
        }
        return stringBuilder.toString();
    }

}
----